version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install
  pre_build:
    commands:
      - npm run test
artifacts:
  type: zip
  files:
    - app.js
    - package.json
    - routes/*
    - views/*
